[package]
name        = "concrust"
version     = "0.0.2"
authors     = ["Alex-Diez <alexvic.amatory@gmail.com>"]
readme      = "README.md"
exclude     = [
  ".gitignore",
  "test/**/*",
]

[lib]
name = "concurrent"
path = "src/lib.rs"

[[test]]
name = "test"
path = "test/mod.rs"

[dependencies]
stainless = { git = "https://github.com/reem/stainless.git" }
